# Generated by Django 4.0 on 2021-12-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_name', models.CharField(max_length=200)),
                ('Job_place', models.CharField(max_length=150)),
                ('Job_Date_From', models.CharField(max_length=50)),
                ('Job_Date_To', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Exp_Model',
                'verbose_name_plural': 'Exp_Models',
            },
        ),
        migrations.CreateModel(
            name='Info_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cv_link', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info_Model',
                'verbose_name_plural': 'Info_Models',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_Img', models.ImageField(upload_to='images/')),
                ('project_desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Portfolio_Model',
                'verbose_name_plural': 'Portfolio_Models',
            },
        ),
    ]
