# Generated by Django 4.0 on 2021-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('progress', models.IntegerField(max_length=50)),
            ],
            options={
                'verbose_name': 'Coding_skill',
                'verbose_name_plural': 'Coding_skillss',
            },
        ),
        migrations.CreateModel(
            name='Design_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('progress', models.IntegerField(max_length=50)),
            ],
            options={
                'verbose_name': 'Design_skill',
                'verbose_name_plural': 'Design_skills',
            },
        ),
    ]
