# Generated by Django 4.0 on 2021-12-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_coding_skills_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coding_skills',
            old_name='skill_name',
            new_name='codeing_skill_name',
        ),
        migrations.RenameField(
            model_name='design_skills',
            old_name='skill_name',
            new_name='design_skill_name',
        ),
    ]
